package flightrising.core;

public enum Colour {
    MAIZE, CREAM, ANTIQUE, WHITE, MOON, ICE, ORCA, PLATINUM, SILVER, DUST, GREY,
    SMOKE, GLOOM, LEAD, SHALE, FLINT, CHARCOAL, COAL, OILSLICK, BLACK, OBSIDIAN,
    ELDRITCH, MIDNIGHT, SHADOW, BLACKBERRY, MULBERRY, PLUM, WISTERIA, THISTLE,
    FOG, MIST, LAVENDER, HEATHER, PURPLE, ORCHID, AMETHYST, NIGHTSHADE, VIOLET,
    GRAPE, ROYAL, EGGPLANT, IRIS, STORM, TWILIGHT, INDIGO, SAPPHIRE, NAVY,
    COBALT, ULTRAMARINE, BLUE, PERIWINKLE, LAPIS, SPLASH, CORNFLOWER, SKY,
    STONEWASH, OVERCAST, STEEL, DENIM, ABYSS, PTHALO, DEEPAZURE, CARIBBEAN,
    TEAL, CERULEAN, CYAN, ROBIN, AQUA, TURQUOISE, SPRUCE, PISTACHIO, SEAFOAM,
    MINT, JADE, SPEARMINT, THICKET, PEACOCK, EMERALD, SHAMROCK, JUNGLE, HUNTER,
    FOREST, CAMO, ALGAE, SWAMP, AVOCADO, GREEN, FERN, MANTIS, PEAR, LEAF,
    RADIOACTIVE, HONEYDEW, PERIDOT, CHARTEUSE, SPRING, CROCODILE, OLIVE, MURK,
    MOSS, GOLDENROD, AMBER, HONEY, LEMON, YELLOW, GRAPFRUIT, BANANA, SANDDOLLAR,
    FLAXEN, IVORY, BUTTERCUP, GOLD, METALS, MARIGOLD, SUNSHINE, SAFFRON, SUNSET,
    PEACH, CANTALOUPE, ORANGE, BRONZE, TERRACOTTA, CARROT, FIRE, PUMPKIN,
    TANGERINE, CINNAMON, SAND, TAN, BEIGE, STONE, TAUPE, SLATE, DRIFTWOOD,
    LATTE, DIRT, CLAY, SABLE, UMBER, SOIL, HICKORY, TARNISH, GINGER, BROWN,
    CHOCOLATE, AUBURN, COPPER, RUST, TOMATO, VERMILLION, RUBY, CHERRY, CRIMSON,
    GARNET, SANGUINE, BLOOD, MAROON, BERRY, RED, STRAWBERRY, CERISE, CARMINE,
    BRICK, CORAL, BLUSH, COTTONCANDY, WATERMELON, MAGENTA, FUCHSIA, RASBERRY,
    WINE, MAUVE, PINK, BUBBLEGUM, ROSE, PEARL;

    public static final int size = Colour.values().length;
}
